### ISSUE TITLE
Remove the secrets_path mechanism (it breaks on Windows)

### ISSUE THREAD

**Issue by elgiad007** [simonw/datasette-auth-existing-cookies#14]
Hello,

I am currently running Datasette version 0.56.  I installed this plugin and updated my metadata.json file but am getting the error below when I start up Datasette. The path cited in the error does not exist, but I'm not sure why it's looking there for anything. I have installed other Datasette plugins and not had this problem.

Here is the output:

Traceback (most recent call last):
  File "c:\users\kim\appdata\local\programs\python\python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\kim\appdata\local\programs\python\python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Kim\AppData\Local\Programs\Python\Python38-32\Scripts\datasette.exe\__main__.py", line 9, in <module>
  File "c:\users\kim\appdata\local\programs\python\python38-32\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\kim\appdata\local\programs\python\python38-32\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\kim\appdata\local\programs\python\python38-32\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\kim\appdata\local\programs\python\python38-32\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\kim\appdata\local\programs\python\python38-32\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\kim\appdata\local\programs\python\python38-32\lib\site-packages\datasette\cli.py", line 530, in serve
    ds = Datasette(files, **kwargs)
  File "c:\users\kim\appdata\local\programs\python\python38-32\lib\site-packages\datasette\app.py", line 329, in __init__
    self.client = DatasetteClient(self)
  File "c:\users\kim\appdata\local\programs\python\python38-32\lib\site-packages\datasette\app.py", line 1358, in __init__
    self.app = ds.app()
  File "c:\users\kim\appdata\local\programs\python\python38-32\lib\site-packages\datasette\app.py", line 1055, in app
    for wrapper in pm.hook.asgi_wrapper(datasette=self):
  File "c:\users\kim\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\users\kim\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\users\kim\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "c:\users\kim\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py", line 208, in _multicall
    return outcome.get_result()
  File "c:\users\kim\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "c:\users\kim\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\users\kim\appdata\local\programs\python\python38-32\lib\site-packages\datasette_auth_existing_cookies\__init__.py", line 29, in asgi_wrapper
    secrets_path.parent.mkdir(exist_ok=True)
  File "c:\users\kim\appdata\local\programs\python\python38-32\lib\pathlib.py", line 1284, in mkdir
    self._accessor.mkdir(self, mode)
**FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\Kim\\AppData\\Local\\datasette-auth-existing-cookies\\datasette-auth-existing-cookies'**

Any help with this would be greatly appreciated.  Thanks!

Luc Daigle

**Comment by simonw** [comment]
I'm going to remove this mechanism: https://github.com/simonw/datasette-auth-existing-cookies/blob/3b3cbcdd45bd8a97f28228896e808b031afa58ea/datasette_auth_existing_cookies/__init__.py#L21-L31

I think I designed this before Datasette had its own mechanism for secrets. I added that in 2020-06-11: https://docs.datasette.io/en/stable/changelog.html#v0-44

**Comment by simonw** [comment]
Here's the rationale behind adding this feature in the first place:
- #1

With hindsight that was clearly unnecessary complexity. It's now removed.
